
drop database if exists test;
create database test;
use test;
create table todos (id int auto_increment, created_at timestamp, todo text not null, done bit(1) not null, todoD date not null, primary key(id));
insert into todos (id, created_at, todo, done, todoD) values ('1', now(), 'Gym', b'0', '17-12-10');
insert into todos (todo, done, todoD) values ('Cleaning', b'0','17-12-10');
insert into todos (todo, done, todoD) values ('Call a teacher', b'0','17-12-10');
insert into todos (todo, done, todoD) values ('Meeting', b'0','17-12-11');
insert into todos (todo, done, todoD) values ('Buy a present', b'0','17-12-11');
insert into todos (todo, done, todoD) values ('Download new music on the phone', b'0','17-12-11');
insert into todos (todo, done, todoD) values ('Get the package from post office', b'0','17-12-12');
insert into todos (todo, done, todoD) values ('Gym', b'0','17-12-12');
insert into todos (todo, done, todoD) values ('Hairdresser', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo1', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo2', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo3', b'0','17-12-14');
insert into todos (todo, done, todoD) values ('todo4', b'0','17-12-14');
insert into todos (todo, done, todoD) values ('todo5', b'0','17-12-15');
insert into todos (todo, done, todoD) values ('todo6', b'0','17-12-15');
insert into todos (todo, done, todoD) values ('todo7', b'0','17-12-16');
insert into todos (todo, done, todoD) values ('todo8', b'0','17-12-17');
insert into todos (todo, done, todoD) values ('todo9', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo10', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo11', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo12', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo13', b'0','17-12-14');
insert into todos (todo, done, todoD) values ('todo14', b'0','17-12-14');
insert into todos (todo, done, todoD) values ('todo15', b'0','17-12-15');
insert into todos (todo, done, todoD) values ('todo16', b'0','17-12-15');
insert into todos (todo, done, todoD) values ('todo17', b'0','17-12-16');
insert into todos (todo, done, todoD) values ('todo18', b'0','17-12-17');
insert into todos (todo, done, todoD) values ('todo19', b'0','17-12-13');
insert into todos (todo, done, todoD) values ('todo20', b'0','17-12-13');